local function testrep(init, rep, close, repc, finalresult)
  local s = init .. string.rep(rep, 100) .. close .. string.rep(repc, 100)
  local res, msg = load(s)
  print("OK100", res ~= nil, msg)
  if finalresult then print("RESULT", res and res()) end
  s = init .. string.rep(rep, 500)
  local res2, msg2 = load(s)
  print("LONG", res2 ~= nil, msg2)
end
testrep("local a; a", ",a", "= 1", ",1")
testrep("local a; a=", "{", "0", "}")
testrep("return ", "(", "2", ")", 2)
testrep("local function a (x) return x end; return ", "a(", "2.2", ")", 2.2)
testrep("", "do ", "", " end")
testrep("", "while a do ", "", " end")
testrep("local a; ", "if a then else ", "", " end")
testrep("", "function foo () ", "", " end")
testrep("local a = ''; return ", "a..", "'a'", "", "a")
testrep("local a = 1; return ", "a^", "a", "", 1)
