local file = os.tmpname()
local f = assert(io.open(file, "w")); f:write("abc\n"); f:close()
io.input(file)
local ok, err = pcall(io.read, "x")
print("invalid", tostring(ok), type(err), tostring(err))
local ok2, err2 = pcall(io.read, 0)
print("zero", tostring(ok2), type(err2), tostring(err2))
os.remove(file)
local file2 = os.tmpname()
local f2 = assert(io.open(file2, "w")); f2:write("x\n"); f2:close()
io.input(file2)
io.close(io.input())
local ok3, err3 = pcall(io.read)
print("closed-default-read", tostring(ok3), type(err3), tostring(err3), tostring(string.find(err3, " input file is closed", 1, true)))
io.output(file2)
io.close()
local ok4, err4 = pcall(io.write, "x")
print("closed-default-write", tostring(ok4), type(err4), tostring(err4), tostring(string.find(err4, " output file is closed", 1, true)))
os.remove(file2)
