local function probe(name, f, ...)
    local ok, err = pcall(f, ...)
    print(name, tostring(ok), type(err), tostring(err))
end
probe("method", io.stdin.close)
probe("stdin", io.close, io.stdin)
probe("stdout", io.stdout.close)
probe("stderr", io.stderr.close)
local close_result = io.close(io.stdin)
print("close-result", type(close_result), tostring(close_result))
local stdout_ok, stdout_result = pcall(function() return io.stdout:close() end)
local stderr_ok, stderr_result = pcall(function() return io.stderr:close() end)
print("method-self", tostring(stdout_ok), type(stdout_result), tostring(stdout_result), tostring(stderr_ok), type(stderr_result), tostring(stderr_result))
local function testerr (msg, f, ...)
    local stat, err = pcall(f, ...)
    return (not stat and string.find(err, msg, 1, true))
end
print("testerr", testerr("got no value", io.stdin.close))
assert(testerr("got no value", io.stdin.close))
