local maxint = math.maxinteger
local file = os.tmpname()
do
  local f = assert(io.open(file, "w"))
  f:write(maxint, '\n')
  f:write(string.format("0X%x\n", maxint))
  f:write("0xABCp-3", '\n')
  f:write(0, '\n')
  f:write(-maxint, '\n')
  f:write(string.format("0x%X\n", -maxint))
  f:write("-0xABCp-3", '\n')
  assert(f:close())
end
local f = assert(io.open(file, "r"))
local function check(label, expected)
  local got = f:read("n")
  print(label, type(got), tostring(got), type(expected), tostring(expected), tostring(got == expected))
  assert(got == expected)
end
check("maxint", maxint)
check("maxint hex", maxint)
check("hex fraction", 0xABCp-3)
check("zero", 0)
check("neg max", -maxint)
check("neg hex", -maxint)
check("neg fraction", -0xABCp-3)
assert(f:close())
assert(os.remove(file))
print("numbers passed")
