local function doit(s)
  local f, msg = load(s)
  if not f then return msg end
  local cond, msg = pcall(f)
  return (not cond) and msg
end
local function check(s, expected)
  local m = doit(s)
  print(expected, m, type(m), m and string.find(m, expected, 1, true) or false)
end
check("a = {} + 1", "arithmetic")
check("a = {} | 1", "bitwise operation")
check("a = {} < 1", "attempt to compare")
check("a = {} <= 1", "attempt to compare")
check("aaa=1; bbbb=2; aaa=math.sin(3)+bbbb(3)", "global 'bbbb'")
check("aaa={}; do local aaa=1 end aaa:bbbb(3)", "method 'bbbb'")
check("local a={}; a.bbbb(3)", "field 'bbbb'")
check("aaa={13}; local bbbb=1; aaa[bbbb](3)", "number")
check("aaa=(1)..{}", "a table value")
check("a = {_ENV = {}}; print(a._ENV.x + 1)", "field 'x'")
check("print(('_ENV').x + 1)", "field 'x'")
check("local a; a(13)", "local 'a'")
check("local a={}; return a.bbbb(3)", "field 'bbbb'")
check("aaa={}; do local aaa=1 end; return aaa:bbbb(3)", "method 'bbbb'")
check("aaa = #print", "length of a function value")
check("aaa = #3", "length of a number value")
check("aaa.bbb:ddd(9)", "global 'aaa'")
check("local aaa={bbb=1}; aaa.bbb:ddd(9)", "field 'bbb'")
check("local aaa={bbb={}}; aaa.bbb:ddd(9)", "method 'ddd'")
check("local a,b,c; (function () a = b+1.1 end)()", "upvalue 'b'")
check("local a,b,cc; (function () a = cc[1] end)()", "upvalue 'cc'")
check("local a,b,cc; (function () a.x = 1 end)()", "upvalue 'a'")
check("local _ENV = {x={}}; a = a + 1", "global 'a'")
check("BB=1; local aaa={}; x=aaa+BB", "local 'aaa'")
check("aaa={}; x=3.3/aaa", "global 'aaa'")
check("aaa=2; BB=nil;x=aaa*BB", "global 'BB'")
check("aaa={}; x=-aaa", "global 'aaa'")
check("local a,b,c,f = 1,1,1; f((a and b) or c)", "local 'f'")
check("local a,b,c = 1,1,1; ((a and b) or c)()", "call a number value")
check("print(print < 10)", "function with number")
check("print(print < print)", "two function values")
check("print('10' < 10)", "string with number")
check("print(10 < '23')", "number with string")
