local function testerr (msg, f, ...)
  local stat, err = pcall(f, ...)
  return (not stat and string.find(err, msg, 1, true))
end
local function checkerr (label, msg, f, ...)
  local value = testerr(msg, f, ...)
  print(label, tostring(value))
  assert(value)
end
local file = os.tmpname()
local f = assert(io.open(file, "w")); f:close()
checkerr("rw", "invalid mode", io.open, file, "rw")
checkerr("rb+", "invalid mode", io.open, file, "rb+")
checkerr("r+bk", "invalid mode", io.open, file, "r+bk")
checkerr("empty", "invalid mode", io.open, file, "")
checkerr("plus", "invalid mode", io.open, file, "+")
checkerr("b", "invalid mode", io.open, file, "b")
assert(io.open(file, "r+b")):close()
assert(io.open(file, "r+")):close()
assert(io.open(file, "rb")):close()
assert(os.setlocale('C', 'all'))
io.input(io.stdin); io.output(io.stdout)
os.remove(file)
print("loadfile", tostring(loadfile(file)))
assert(not loadfile(file))
checkerr("dofile", "", dofile, file)
assert(not io.open(file))
print("early passed")
