[package]
name = "blu-lang"
description = "High-performance Rust runtime for Luau, Lua, and the Blu language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
blu-bytecode.workspace = true
blu-runtime.workspace = true

