[package]
name = "blu-lang"
description = "Embeddable Lua and Luau superset language runtime for Rust"
keywords = ["lua", "luau", "interpreter", "runtime", "embedded-scripting"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
blu-bytecode.workspace = true
blu-compiler = { workspace = true, features = ["legacy-luau"] }
blu-core.workspace = true
blu-package.workspace = true
blu-runtime.workspace = true
