[package]
name = "blu-runtime"
description = "High-performance Lua-family runtime and interpreter for Blu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
blu-bytecode.workspace = true
