[package]
name = "blu-runtime"
description = "Embeddable Lua and Luau interpreter and virtual machine for Blu"
keywords = ["lua", "luau", "interpreter", "runtime", "virtual-machine"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
blu-bytecode.workspace = true
